core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("membership.urls", namespace="membership"))
]

membership/urls.py
from django.urls import path
from .views import checkout_cancel, checkout_success, index, create_checkout_session, webhook

app_name = "membership"

urlpatterns = [
    path("", index, name="index"),
    path("create-checkout-session/", create_checkout_session, name="create-checkout-session"),
    path("success/session_id=<id>/", checkout_success, name="checkout-success"),
    path("cancel-membership/", checkout_cancel, name="checkout-cancel"),
    path("membership-webhook/", webhook, name="membership-webhook"),
]

membership/models.py
from django.db import models

# Create your models here.

membership/views.py
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
import stripe

YOUR_DOMAIN = "http://localhost:8000"

stripe.api_key = "sk_test_"


def index(request):
    return render(request, "membership/index.html")


def create_checkout_session(request):
    if request.method == "POST":
        try:
            prices = stripe.Price.list(
                lookup_keys=[].append(request.POST["lookup_key"]),
                expand=["data.product"],
            )
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=["card"],
                line_items=[
                    {
                        "price": prices.data[0].id,
                        "quantity": 1,
                    },
                ],
                mode="subscription",
                success_url=YOUR_DOMAIN + "/success/session_id={CHECKOUT_SESSION_ID}",
                cancel_url=YOUR_DOMAIN + "/cancel-membership/",
            )
            return redirect(checkout_session.url)
        except Exception as e:
            print(e)
            return "Server error", 500


def checkout_success(request, id):
    return render(request, "membership/success.html", {id: id})


def checkout_cancel(request):
    return render(request, "membership/cancel.html")

endpoint_secret = "whsec_"

@csrf_exempt
def webhook(request):
    event = None
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']

    try:
        event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)
    except ValueError as e:
        raise e
    except stripe.error.SignatureVerificationError as e:
        raise e

    # Handle the event
    if event["type"] == "payment_intent.succeeded":
        payment_intent = event["data"]["object"]
        print(payment_intent)
    else:
        print("Unhandled event type {}".format(event["type"]))

    return HttpResponse(status=200)

membership/templates/membership/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
  <title>Stripe Membership</title>
</head>

<body>
  <div class="container vh-100">
    <div class="row d-flex justify-content-center align-items-center vh-100">
      <div class="col-lg-6 col-12 text-center">
        <div class="card shadow p-3 bg-body rounded">
          {% block content %}{% endblock content %}
        </div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
    crossorigin="anonymous"></script>
</body>

</html>

membership/templates/membership/cancel.html
{% extends 'membership/base.html' %}
{% block content %}
  <section>
    <p>Picked the wrong subscription? Shop around then come back to pay!</p>
  </section>
{% endblock content %}

membership/templates/membership/index.html
{% extends 'membership/base.html' %}
{% block content %}
<h1 class="title">
    Hi, John
</h1>
<p class="subtitle">
    Please make a payment with <strong>Stripe</strong>!
</p>
<div class="card mb-2 mx-auto shadow-sm p-3 mb-3 bg-body rounded" style="width: 18rem;">
    <div class="card-body">
        <h5><svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                class="bi bi-circle-square" viewBox="0 0 16 16">
                <path d="M0 6a6 6 0 1 1 12 0A6 6 0 0 1 0 6z" />
                <path
                    d="M12.93 5h1.57a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-1.57a6.953 6.953 0 0 1-1-.22v1.79A1.5 1.5 0 0 0 5.5 16h9a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 4h-1.79c.097.324.17.658.22 1z" />
            </svg></h5>
        <h5 class="card-title">Premium Membership</h5>
        <p class="card-text">Get access to all the premium features</p>
    </div>
</div>

<form action="{% url 'membership:create-checkout-session' %}" method="post" class="d-grid">
{% csrf_token %}
    <input type="hidden" name="lookup_key" value="price_1JZEL14JaSmpe0Llzqi8CG0C" />
    <button type="submit" href="#" class="btn btn-dark"><svg
            xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-credit-card me-1"
            viewBox="0 0 16 16">
            <path
                d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v1h14V4a1 1 0 0 0-1-1H2zm13 4H1v5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V7z" />
            <path d="M2 10a1 1 0 0 1 1-1h1a1 1 0 0 1 1 1v1a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1v-1z" />
        </svg> Pay</button>
</form>
{% endblock content %}

membership/templates/membership/success.html
{% extends 'membership/base.html' %}
{% block content %}
<div class="product Box-root">
  <h3>Subscription to Premium plan successful!</h3>
{% endblock content %}